radio:
  static:
    - "74938__digifishmusic__radio-static-short-wave-very-quiet.wav"
  stations:
    -
      music: "Abbott and Costello Whos On First.mp3"
      station: 97.5
      gpio: 1
logging:
  level: "info"