# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: build
    silent: true

  build:
    cmds:
      - go build -o radio cmd/main.go
    silent: true

  run:
    cmds:
      - ./radio monitor
      
  lint:
    cmds:
      - golangci-lint run cmd/main.go